### ISSUE TITLE
In causual mode, this expression will lead to a null tensor 'out'

### ISSUE THREAD

**Issue by ZhihaoDU** [ksw0306/FloWaveNet#3] opened 2018-11-13 03:49 UTC
https://github.com/ksw0306/FloWaveNet/blob/c436e128cbb03ccb30e5e05ed1f3c88451aafe75/modules.py#L20-25

I fix this bug by replace this expression with
     out = out[:, :, :out.size(2)-self.padding]
and this code work well in causal mode.

**Comment by L0SG** [comment] 2018-11-13 05:20
Thank you for the bug report! We've reproduced the issue and it's caused by mistakenly cleaning up some of the code for the GitHub release. We'll commit our original working version, which has the same effect when the self.padding gets 0.

**Comment by L0SG** [comment] 2018-11-13 05:24
Fixed by [the last commit](https://github.com/ksw0306/FloWaveNet/commit/cccb46edbd01c9c8185ccf048a741cd7c4a47202).

**Closed as completed by L0SG** 2018-11-13 05:24 UTC
